# Generated by Django 5.2.10 on 2026-01-30 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('celulares', 'Celulares'), ('accesorios', 'Accesorios'), ('repuestos', 'Repuestos'), ('servicios', 'Servicios')], max_length=50),
        ),
    ]
