# Generated by Django 5.2.10 on 2026-01-30 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_producto_imagen_alter_producto_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='destacado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('celulares', 'Celulares'), ('accesorios', 'Accesorios'), ('repuestos', 'Repuestos'), ('servicios', 'Servicios')], default='celulares', max_length=50),
        ),
    ]
