# Generated by Django 5.2.10 on 2026-02-04 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_producto_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='stock',
        ),
    ]
